[package]
name = "trojan-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
description = "Core types and constants for trojan-rs"
keywords = ["trojan", "proxy"]
categories = ["network-programming"]

[dependencies]
